# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Najdi Malíčka | Hledání ztracených zvířat pomocí cílených FB kampaní
description: Ztratil se Vám domácí mazlíček? Náš tým Vám ho pomůže najít pomocí detailně cílených kampaní na sociálních sítích.
keywords: NajdiMazlíčka, Najdi Malíčka, registrace ztráty, psí detektiv, ztraceni psi, ztratil se pes, ztráta kočky, hledání ztracených psů, hledáme kočku, pátrání po ztracených psech, ztracený pes, zatoulaná kočka, ztratila se kočka, hledáme psa, hledá se pes, ztráta psa, ztratila se mi kočka, hledání ztracených koček, zaběhnutý pes, zatoulaný pes, ztracené kočky, ztratil se mi pes, hledá se kočka, zaběhnutá kočka, ztracení psi
author: palmmedia.co
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://najdimazlicka.cz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
    style: compressed
